name: suggest_a_feature
description: Ready-made Flutter package for collecting suggestions from users.
version: 0.1.2
repository: https://github.com/What-the-Flutter/Suggest-a-Feature

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  rxdart: ^0.27.7
  wtf_sliding_sheet: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  very_good_analysis: ^5.0.0+1

flutter:
  assets:
    - assets/
