name: suggest_a_feature
description: Ready-made Flutter package for collecting suggestions from users.
version: 0.1.1
repository: https://github.com/What-the-Flutter/Suggest-a-Feature

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  extended_image: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  intl: ^0.18.0
  rxdart: ^0.27.7
  wtf_sliding_sheet: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^5.0.0+1

flutter:
  assets:
    - assets/
