name: suggest_a_feature
description: Ready-made Flutter package for collecting suggestions from users.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  extended_image: ^6.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^0.13.5
  intl: ^0.17.0
  rxdart: ^0.27.7

  sliding_sheet:
    git:
      url: https://github.com/flutterwtf/sliding_sheet
      ref: master

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^3.1.0

flutter:
  assets:
    - assets/
